/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HeroImage: typeof import('./src/components/HeroImage.vue')['default']
    ModalError: typeof import('./src/components/ModalError.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
  }
}
