/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Carousel: typeof import('./src/components/services-page/chatbot-ai/Carousel.vue')['default']
    CharacterIntro: typeof import('./src/components/landing-page/CharacterIntro.vue')['default']
    Chatbot: typeof import('./src/components/landing-page/Chatbot.vue')['default']
    ChatbotContent: typeof import('./src/components/ChatbotContent.vue')['default']
    ChatbotPage: typeof import('./src/components/chatbot-page/ChatbotPage.vue')['default']
    ChatbotService: typeof import('./src/components/services/chatbot-ai/ChatbotService.vue')['default']
    ChatCollapse: typeof import('./src/components/chatbot-page/ChatCollapse.vue')['default']
    ChatLis: typeof import('./src/components/chatbot-page/ChatLis.vue')['default']
    ChatList: typeof import('./src/components/chatbot-page/ChatList.vue')['default']
    ChatMenu: typeof import('./src/components/chatbot-page/ChatMenu.vue')['default']
    ChatNavbar: typeof import('./src/components/chatbot-page/ChatNavbar.vue')['default']
    ChatWIndow: typeof import('./src/components/chatbot-page/ChatWIndow.vue')['default']
    Content: typeof import('./src/components/services-page/chatbot-ai/Content.vue')['default']
    DiseaseCard: typeof import('./src/components/services-page/chatbot-ai/DiseaseCard.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    HealthFeatures: typeof import('./src/components/HealthFeatures.vue')['default']
    HealthServices: typeof import('./src/components/HealthServices.vue')['default']
    HealthServicesModal: typeof import('./src/components/HealthServicesModal.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    HeroImage: typeof import('./src/components/HeroImage.vue')['default']
    LandingHero: typeof import('./src/components/landing-page/LandingHero.vue')['default']
    LandingImage: typeof import('./src/components/landing-page/LandingImage.vue')['default']
    LandingPage: typeof import('./src/components/landing-page/LandingPage.vue')['default']
    Loading: typeof import('./src/components/common/Loading.vue')['default']
    ModalError: typeof import('./src/components/common/ModalError.vue')['default']
    Navbar: typeof import('./src/components/common/Navbar.vue')['default']
    Services: typeof import('./src/components/services/Services.vue')['default']
    ServicesContent: typeof import('./src/components/services-page/ServicesContent.vue')['default']
    ServicesHero: typeof import('./src/components/services-page/ServicesHero.vue')['default']
    ServicesPage: typeof import('./src/components/services-page/ServicesPage.vue')['default']
    SideBar: typeof import('./src/components/chatbot-page/SideBar.vue')['default']
    SpecialistCard: typeof import('./src/components/SpecialistCard.vue')['default']
    SpecialistContent: typeof import('./src/components/landing-page/SpecialistContent.vue')['default']
    SpecialistModal: typeof import('./src/components/landing-page/SpecialistModal.vue')['default']
    TabSelect: typeof import('./src/components/common/TabSelect.vue')['default']
  }
}
